name: Laravel CI + FTP Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  laravel-ci-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step 2: Setup PHP
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    # Step 3: Install Composer Dependencies
    - name: Install Composer Dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    # Step 4: Copy .env if not present
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    # Step 5: Generate Application Key
    - name: Generate App Key
      run: php artisan key:generate

    # Step 6: Set Directory Permissions
    - name: Set Permissions
      run: chmod -R 777 storage bootstrap/cache

    # Step 7: Setup SQLite DB for Tests
    - name: Create SQLite DB
      run: |
        mkdir -p database
        touch database/database.sqlite

    # Step 8: Run Laravel Tests
    - name: Run Tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test

    # Step 9: FTP Deploy to cPanel
    - name: 📦 FTP Deploy to cPanel
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./  # root of your Laravel project
        server-dir: /  # change this to your cPanel target path
        exclude: |
          **/.git*
          **/node_modules/**
          **/vendor/**
          .env
